[package]
name = "maint"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
clap = { version = "4.5.47", features = ["derive"] }
rusqlite = "0.37.0"
serde_yaml = "0.9.34"
edit = "0.1.5"
serde = { version = "1.0.228", features = ["derive"] }
